confirm_profile_update_link:
    path: /vendor/profile-update/{token}
    methods: [GET]
    defaults:
        _controller: open_marketplace.controller.confirm_profile_update_action
        _sylius:
            template: "Vendor/Profile/update.html.twig"
            form: BitBag\OpenMarketplace\Form\Type\VendorType
            event: update
            repository:
                method: findOneByActivationToken
                arguments:
                    token: $token
