open_marketplace:
    resource: |
        alias: open_marketplace.conversation
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show', 'update', 'bulk_delete']
        redirect: index
        grid: open_marketplace_admin_conversation
        permission: true
        vars:
            all:
                header: open_marketplace.ui.conversations_listing.admin_header
                subheader: open_marketplace.ui.conversations_listing.admin_subheader
    type: sylius.resource
    prefix: /admin

open_marketplace_admin_conversation_create:
    path: /admin/conversation/create
    methods: [GET,POST]
    defaults:
        _controller: bitbag.open_marketplace.component.core.common.controller.messaging.create_thread
        _sylius:
            template: "Context/Admin/Conversation/create.html.twig"
            redirect: open_marketplace_admin_conversation_show
            mail_redirect: mvm_vendor_conversation_show

open_marketplace_admin_conversation_show:
    path: /admin/conversations/{id}
    methods: [GET,POST]
    defaults:
        _controller: bitbag.open_marketplace.component.core.common.controller.messaging.show_thread
        _sylius:
            template: "Context/Admin/Conversation/show.html.twig"

open_marketplace_admin_conversation_archive:
    path: /admin/conversations/{id}/archive
    methods: [GET,POST]
    defaults:
        _controller: bitbag.open_marketplace.component.core.admin.controller.messaging.send_archive_request
        _sylius:
            redirect: open_marketplace_admin_conversation_index


open_marketplace_admin_conversation_message_add:
    path: /admin/conversations/{id}/message/add
    methods: [GET, POST]
    defaults:
        _controller: bitbag.open_marketplace.component.core.common.controller.messaging.create_message
        _sylius:
            redirect: open_marketplace_admin_conversation_show
            mail_redirect: open_marketplace_admin_conversation_show

