sylius_grid:
    templates:
        action:
            archiveConversation: "Admin/Conversation/_archiveConversation.html.twig"
    grids:
        open_marketplace_admin_conversation:
            driver:
                name: doctrine/orm
                options:
                    class: "%open_marketplace.model.conversation.class%"
            fields:
                category:
                    type: twig
                    label: open_marketplace.ui.form.conversation.category
                    options:
                        template: 'Admin/Conversation/_category.html.twig'
                shopUser:
                    type: twig
                    label: open_marketplace.ui.grid.conversation.applicant
                    options:
                        template: 'Admin/Conversation/_applicant.html.twig'
            filters:
                status:
                    label: open_marketplace.ui.status
                    type: select
                    form_options:
                        choices:
                            open_marketplace.ui.open: open
                            open_marketplace.ui.closed: closed
                createdAt:
                    type: date
                    label: sylius.ui.date
                    options:
                        field: messages.createdAt
                        inclusive_to: true
            actions:
                main:
                    create:
                        type: create
                        options:
                            link:
                                route: open_marketplace_admin_conversation_create
                item:
                    show:
                        type: show
                    delete:
                        type: delete
                    archive:
                        type: archiveConversation
                        label: open_marketplace.ui.grid.conversation.archive
