api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Resources/config/api_resources'
            - '%kernel.project_dir%/config/api_platform'
            - '%kernel.project_dir%/src/Api/Resources/api_resources'
            - '%kernel.project_dir%/src/Component/Messaging/Entity'
            - '%kernel.project_dir%/src/Component/Order/Entity'
            - '%kernel.project_dir%/src/Component/Product/Entity'
            - '%kernel.project_dir%/src/Component/ProductListing/Entity'
            - '%kernel.project_dir%/src/Component/Vendor/Entity'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
