parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: UTF8
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: 'Ramsey\Uuid\Doctrine\UuidType'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            MessagingComponent:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Component/Messaging/Resources/doctrine'
                prefix: 'BitBag\OpenMarketplace\Component\Messaging\Entity'
            OrderComponent:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Component/Order/Resources/doctrine'
                prefix: 'BitBag\OpenMarketplace\Component\Order\Entity'
            ProductComponent:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Component/Product/Resources/doctrine'
                prefix: 'BitBag\OpenMarketplace\Component\Product\Entity'
            ProductListingComponent:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Component/ProductListing/Resources/doctrine'
                prefix: 'BitBag\OpenMarketplace\Component\ProductListing\Entity'
            VendorComponent:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Component/Vendor/Resources/doctrine'
                prefix: 'BitBag\OpenMarketplace\Component\Vendor\Entity'
            SettlementComponent:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Component/Settlement/Resources/doctrine'
                prefix: 'BitBag\OpenMarketplace\Component\Settlement\Entity'
