# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en_US

imports:
    - { resource: "../src/Component/Core/Admin/Resources/services.xml" }
    - { resource: "../src/Component/Core/Common/Resources/services.xml" }
    - { resource: "../src/Component/Core/Shop/Resources/services.xml" }
    - { resource: "../src/Component/Core/Vendor/Resources/services.xml" }
    - { resource: "../src/Component/Messaging/Resources/services.xml" }
    - { resource: "../src/Component/Order/Resources/services.xml" }
    - { resource: "../src/Component/Override/Resources/services.xml" }
    - { resource: "../src/Component/ProductListing/Resources/services.xml" }
