winzou_state_machine:
    mvm_product_listing:
        class: '%bitbag_mvm_plugin.model.product_draft.class%'
        property_path: status
        graph: product_draft
        state_machine_class: "%sylius.state_machine.class%"
        states:
            created: ~
            under_verification: ~
            accepted: ~
            rejected: ~
        transitions:
            send_to_verification:
                from: ['created']
                to: 'under_verification'
            accept_product_draft:
                from: ['under_verification']
                to: 'accepted'
            reject_product_draft:
                from: ['under_verification']
                to: 'rejected'
        callbacks:
            after:
                send_to_verification:
                    on: [ 'send_to_verification' ]
                    do: [ '@bitbag_mvm_plugin.state_machine.product_draft', 'sendToVerify' ]
                    args: [ 'object' ]
                accept_product_listing:
                    on: ['accept_product_draft']
                    do: ['@bitbag_mvm_plugin.state_machine.product_draft', 'accept']
                    args: ['object']
                reject_product_listing:
                    on: [ 'reject_product_draft' ]
                    do: [ '@bitbag_mvm_plugin.state_machine.product_draft', 'reject' ]
                    args: [ 'object' ]
