sylius_grid:
  templates:
    action:
      details: 'Grid/Action/product_details.html.twig'
      restore: 'Grid/Action/restore.html.twig'
    filter:
      product_listing_status: 'Grid/Filter/product_listing_status.html.twig'
  grids:
    open_marketplace_admin_product_listing:
      driver:
        name: doctrine/orm
        options:
          class: BitBag\OpenMarketplace\Entity\ProductListing\ProductListing
          repository:
            method: createQueryBuilderWithLatestDraft
      sorting:
        id: desc
      filters:
        search:
          type: string
          form_options:
            type: contains
          options:
            fields: ['code', 'vendor.companyName', 'vendor.shopUser.customer.firstName', 'vendor.shopUser.customer.lastName']
        vendor:
          type: entity
          label: open_marketplace.ui.vendor
          form_options:
            class: "BitBag\\OpenMarketplace\\Entity\\Vendor"
        status:
          type: product_listing_status
          label: open_marketplace.ui.status
      fields:
        id:
          type: string
          label: open_marketplace.ui.id
          sortable: ~
        code:
          type: string
          label: open_marketplace.ui.code
          sortable: ~
        anyTranslationName:
          type: twig
          label: sylius.ui.name
          sortable: latestDraft.translations.name
          options:
            template: "Grid/Field/product_listing_name.html.twig"
        vendor:
          type: twig
          label: open_marketplace.ui.vendor
          sortable: vendor.companyName
          options:
            template: "Grid/Field/product_listing_vendor.html.twig"
        publishedAt:
          type: datetime
          label: open_marketplace.ui.published_at
          sortable: ~
        lastVerifiedAt:
          type: datetime
          label: open_marketplace.ui.verified_at
          sortable: ~
        verificationStatus:
          type: twig
          label: open_marketplace.ui.status
          sortable: ~
          options:
            template: "Grid/Field/product_listing_status.html.twig"
      actions:
        item:
          details:
            type: details
            label: open_marketplace.ui.details
            options:
              link:
                route: open_marketplace_admin_product_listing_show
                parameters:
                  id: resource.id
          restore_visibility:
            type: restore
