sylius_mailer:
    sender:
        name: 'example owner name'
        address: no-reply@example.com
    emails:
        vendor_profile_update:
            template: "Vendor/Email/profileUpdate.html.twig"
