open_marketplace_admin_product_listing:
    resource: |
        alias: open_marketplace.product_listing
        section: admin
        templates: '@SyliusAdmin/Crud'
        only: ['index']
        redirect: index
        grid: open_marketplace_admin_product_listing
    type: sylius.resource

open_marketplace_admin_product_listing_show:
  path: /product-listings/{id}
  defaults:
    _controller: open_marketplace.controller.action.admin.product_listing.show_action
    _sylius:
      section: admin
      template: 'Admin/ProductListing/show_product_listing.html.twig'
      permission: true

open_marketplace_admin_product_listing_accept:
  path: /product-listings/{id}/accept
  defaults:
    _controller: open_marketplace.controller.action.admin.product_listing.accept_action
    _sylius:
      section: admin
      permission: true

open_marketplace_admin_product_listing_reject:
  path: /product-listings/{id}/reject
  defaults:
    _controller: open_marketplace.controller.action.admin.product_listing.reject_action
    _sylius:
      section: admin
      permission: true

open_marketplace_admin_product_listing_restore:
    path: /product-listings-restore/{id}
    defaults:
        _controller: open_marketplace.controller.product_listing.restore_action
        _sylius:
            section: admin
            permission: true
